config/routes.rb
Hashtag::Application.routes.draw do
  root to: 'searches#new'
  resources :searches, only: [:create, :show]
end

app/models/fake_twitter.rb
class FakeTwitter
	def self.[]=(term, results)
		@data ||= {}
		@data[term] = results
	end

	def self.search(term)
		# results = @data[term].map {|hash| Twitter::Status.new(hash.merge(id: 1)) }
		@data ||= {}	
		results = @data.fetch(term, []).map do |hash|
			hash_with_id = hash.merge(id: 1)
			Twitter::Status.new(hash_with_id)
		end

		OpenStruct.new(results: results)
	end

	def self.clear
		@data = {}
	end
end

app/models/searcher.rb
class Searcher
	class_attribute :backend
	self.backend = Twitter

	def initialize(term)
		@term = term
	end

	def each(&block)
		# class attributes allow setting attributes on a class level and on an instance level (below):
		tweets.each(&block)
	end

	def length
		tweets.length
	end

	private

	def tweets
    @tweets ||= backend.search(@term).results
  end
end

# this allows for something like :
# Searcher.backend = FakeTwitter 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def create
    search_term = params[:search][:search].gsub(/#/, '')
    redirect_to search_path(search_term)
  end

  def show
    @tweets = Searcher.new("##{params[:id]}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hashtag</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/new.html.erb
<%= form_for :search, url: searches_path do |form| %>
  <%= form.label :search %>
  <%= form.text_field :search %>
  <%= form.submit 'Submit' %>
<% end %>

app/views/searches/show.html.erb
<%= form_for :search, url: searches_path do |form| %>
  <%= form.label :search %>
  <%= form.text_field :search %>
  <%= form.submit 'Submit' %>
<% end %>

<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <%= tweet.text %>
      <span class='author'><%= tweet.from_user %></span>
    </li>
  <% end %>
</ul>